apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ng.fullname" . }}-app
  labels:
    {{- include "paperless-ng.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "paperless-ng.selectorLabels" . | nindent 4 }}
